// auto-generated by typings-for-css-modules-loader
declare namespace AboutScssNamespace {
  export interface IAboutScss {
    fadeIn: string;
    fadeOut: string;
    photo: string;
    rotating: string;
    socialLine: string;
    socialLineIcon: string;
    socialLineText: string;
    socialLineWrapper: string;
    text: string;
    wrapper: string;
  }
}

declare const AboutScssModule: AboutScssNamespace.IAboutScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: AboutScssNamespace.IAboutScss;
};

export = AboutScssModule;
