// auto-generated by typings-for-css-modules-loader

declare namespace GalleryScssModule {
  export interface IGalleryScss {
    buttonsLine: string;
    fadeIn: string;
    fadeOut: string;
    gallery: string;
    item: string;
    loading: string;
    rotating: string;
    uploadButton: string;
  }
}

declare const GalleryScssModule: GalleryScssModule.IGalleryScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: GalleryScssModule.IGalleryScss;
};

export = GalleryScssModule;
