// auto-generated by typings-for-css-modules-loader

declare namespace FormScssModule {
  export interface IFormScss {
    arrow: string;
    big: string;
    currentValue: string;
    disabled: string;
    errorItem: string;
    errors: string;
    fadeIn: string;
    fadeOut: string;
    focused: string;
    hasErrors: string;
    hasValue: string;
    inputWrapper: string;
    labelPointer: string;
    loading: string;
    rotating: string;
    selectBlock: string;
    submitWrapper: string;
  }
}

declare const FormScssModule: FormScssModule.IFormScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: FormScssModule.IFormScss;
};

export = FormScssModule;
