// auto-generated by typings-for-css-modules-loader
declare namespace ReviewsScssNamespace {
  export interface IReviewsScss {
    fadeIn: string;
    fadeOut: string;
    rotating: string;
    wrapper: string;
  }
}

declare const ReviewsScssModule: ReviewsScssNamespace.IReviewsScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ReviewsScssNamespace.IReviewsScss;
};

export = ReviewsScssModule;
