// auto-generated by typings-for-css-modules-loader
declare namespace ModalsScssNamespace {
  export interface IModalsScss {
    backdrop: string;
    close: string;
    fadeIn: string;
    fadeOut: string;
    leaving: string;
    modal: string;
    modalButton: string;
    modalButtons: string;
    modalContent: string;
    modalTitle: string;
    modals: string;
    rotating: string;
  }
}

declare const ModalsScssModule: ModalsScssNamespace.IModalsScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ModalsScssNamespace.IModalsScss;
};

export = ModalsScssModule;
