export const system = {
  INPUT_MAX_LENGTH: 250,
  MODALS_BASE_Z_INDEX: 12,
  TEXTAREA_MAX_LENGTH: 8000,
  MODALS_LEAVING_TIMEOUT: 300,
  LIGHTBOX_LEAVING_TIMEOUT: 300,
  SPACE_BEFORE_INPUT_TOP_OFFSET: 20,
};
