// auto-generated by typings-for-css-modules-loader

declare namespace LightboxScssModule {
  export interface ILightboxScss {
    arrowLeft: string;
    arrowRight: string;
    backdrop: string;
    close: string;
    fadeIn: string;
    fadeOut: string;
    leaving: string;
    lightbox: string;
    loaded: string;
    rotating: string;
    spinner: string;
  }
}

declare const LightboxScssModule: LightboxScssModule.ILightboxScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: LightboxScssModule.ILightboxScss;
};

export = LightboxScssModule;
