// auto-generated by typings-for-css-modules-loader
declare namespace EditLocalizationScssNamespace {
  export interface IEditLocalizationScss {
    fadeIn: string;
    fadeOut: string;
    input: string;
    item: string;
    loading: string;
    rotating: string;
    saveButton: string;
    textarea: string;
    translations: string;
    value: string;
  }
}

declare const EditLocalizationScssModule: EditLocalizationScssNamespace.IEditLocalizationScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: EditLocalizationScssNamespace.IEditLocalizationScss;
};

export = EditLocalizationScssModule;
