// auto-generated by typings-for-css-modules-loader

declare namespace GlobalScssModule {
  export interface IGlobalScss {
    fadeIn: string;
    fadeOut: string;
    rotating: string;
  }
}

declare const GlobalScssModule: GlobalScssModule.IGlobalScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: GlobalScssModule.IGlobalScss;
};

export = GlobalScssModule;
