// auto-generated by typings-for-css-modules-loader
declare namespace SpinnerScssNamespace {
  export interface ISpinnerScss {
    fadeIn: string;
    fadeOut: string;
    rotating: string;
    spinner: string;
  }
}

declare const SpinnerScssModule: SpinnerScssNamespace.ISpinnerScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: SpinnerScssNamespace.ISpinnerScss;
};

export = SpinnerScssModule;
