// auto-generated by typings-for-css-modules-loader

declare namespace IconScssModule {
  export interface IIconScss {
    fadeIn: string;
    fadeOut: string;
    icon: string;
    rotating: string;
  }
}

declare const IconScssModule: IconScssModule.IIconScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: IconScssModule.IIconScss;
};

export = IconScssModule;
