// auto-generated by typings-for-css-modules-loader
declare namespace IconScssNamespace {
  export interface IIconScss {
    fadeIn: string;
    fadeOut: string;
    icon: string;
    rotating: string;
  }
}

declare const IconScssModule: IconScssNamespace.IIconScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: IconScssNamespace.IIconScss;
};

export = IconScssModule;
