// auto-generated by typings-for-css-modules-loader

declare namespace HeaderScssModule {
  export interface IHeaderScss {
    active: string;
    buttonsBlock: string;
    fadeIn: string;
    fadeOut: string;
    header: string;
    logout: string;
    menu: string;
    menuItem: string;
    rotating: string;
    themeToggler: string;
    title: string;
    topRightBlock: string;
  }
}

declare const HeaderScssModule: HeaderScssModule.IHeaderScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: HeaderScssModule.IHeaderScss;
};

export = HeaderScssModule;
