// auto-generated by typings-for-css-modules-loader

declare namespace NotificationsScssModule {
  export interface INotificationsScss {
    close: string;
    error: string;
    fadeIn: string;
    fadeOut: string;
    info: string;
    leaving: string;
    notification: string;
    notificationInner: string;
    notifications: string;
    rotating: string;
    success: string;
    visible: string;
  }
}

declare const NotificationsScssModule: NotificationsScssModule.INotificationsScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: NotificationsScssModule.INotificationsScss;
};

export = NotificationsScssModule;
