// auto-generated by typings-for-css-modules-loader
declare namespace ErrorPageScssNamespace {
  export interface IErrorPageScss {
    cloud: string;
    cloudWrapper: string;
    errorReason: string;
    errorSubtitle: string;
    errorTitle: string;
    fadeIn: string;
    fadeOut: string;
    moveclouds: string;
    rotating: string;
    textContainer: string;
    wrapper: string;
    x0: string;
    x1: string;
    x2: string;
    x3: string;
    x4: string;
    x5: string;
  }
}

declare const ErrorPageScssModule: ErrorPageScssNamespace.IErrorPageScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ErrorPageScssNamespace.IErrorPageScss;
};

export = ErrorPageScssModule;
