// auto-generated by typings-for-css-modules-loader
declare namespace ModalsCollectionScssNamespace {
  export interface IModalsCollectionScss {
    buttonsLine: string;
    fadeIn: string;
    fadeOut: string;
    fullWidth: string;
    loading: string;
    modalUploadImage: string;
    removeButton: string;
    rotating: string;
    saveButton: string;
  }
}

declare const ModalsCollectionScssModule: ModalsCollectionScssNamespace.IModalsCollectionScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: ModalsCollectionScssNamespace.IModalsCollectionScss;
};

export = ModalsCollectionScssModule;
