/**
 * @docs: https://github.com/TeamSupercell/typings-for-css-modules-loader
 *
 */

export const loaderCssTypings = {
  loader: '@teamsupercell/typings-for-css-modules-loader',
  options: {
    banner: '// auto-generated by typings-for-css-modules-loader',
    formatter: 'prettier',
  },
};
