/**
 * @docs: https://github.com/TeamSupercell/typings-for-css-modules-loader
 *
 */

import webpack from 'webpack';

export const loaderCssTypings: webpack.RuleSetLoader = {
  loader: '@teamsupercell/typings-for-css-modules-loader',
  options: {
    banner: '// auto-generated by typings-for-css-modules-loader',
    formatter: 'prettier',
  },
};
